/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM
    id("org.jetbrains.kotlin.jvm").version("1.3.10")
}

allprojects {
    apply(plugin = "org.jetbrains.kotlin.jvm")
    dependencies {
        // Use the Kotlin JDK 8 standard library
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

        // Use the Kotlin test library
        testImplementation("org.jetbrains.kotlin:kotlin-test")

        // Use the Kotlin JUnit integration
        testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
        testImplementation("junit:junit:4.12")
    }

    repositories {
        // Use jcenter for resolving your dependencies.
        // You can declare any Maven/Ivy/file repository here.
        jcenter()
    }
}

subprojects {
    version = "1.0"
}

configure(subprojects.filter { it.name != "common" }) {
    apply(plugin = "application")

    dependencies {
        implementation(project(":common"))
    }
}

